url: "https://uvaditalia.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Uva d'Italia" # the name of your site, e.g. ACME Corp.
tagline: "Wine grapes imported from Italy for UK distribution"
description: "Uva d'Italia specialises in the import of Italian grapes. Winemaking has been the family business for over three generations. We aim to share our passion for wine by supplying the U.K. with the highest selection of wine grapes from Italy. Enjoy producing homemade wine from the finest grapes Italy has to offer. From four different grape varieties, you can be sure of creating quality wine. All of our grapes have been handpicked and brought over from the heart of Italy. We take great care to deliver grapes that ensure your wine is of the highest-quality. Please note that the wine grapes are seasonal until August 2022. Deliveries will run from August to October. Pre-orders are available."
logo: "assets/images/logo_white_background.jpg"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag