url: "https://www.uvaditalia.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Wine Grapes for Sale UK | Uva d'Italia" # the name of your site, e.g. ACME Corp.
tagline: Wine grapes imported from Italy for UK distribution
description: Our wine grapes are handpicked from Italy. Produce your home-made wine from the finest wine grapes of Italy, including Montepulciano, Merlot, Syrah and Trebbiano. Wine-making has been the family business for over three generations. We aim to share our passion for wine by supplying wine grapes to the U.K. with the highest selection of wine grapes from Italy. We take great care to deliver grapes that ensure your wine is of the highest quality. Please note that the wine grapes are seasonal until August 2022. Deliveries will run from August to October. Pre-orders are available.
logo: ../assets/images/logo_white_background.jpg

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag